tests/cpychecker/refcounts/PySys_GetObject/incorrect/input.c: In function 'test':
tests/cpychecker/refcounts/PySys_GetObject/incorrect/input.c:29:nn: warning: ob_refcnt of return value is 1 too low [enabled by default]
tests/cpychecker/refcounts/PySys_GetObject/incorrect/input.c:29:nn: note: was expecting final ob_refcnt to be N + 1 (for some unknown N)
tests/cpychecker/refcounts/PySys_GetObject/incorrect/input.c:29:nn: note: due to object being referenced by: return value
tests/cpychecker/refcounts/PySys_GetObject/incorrect/input.c:29:nn: note: but final ob_refcnt is N + 0
tests/cpychecker/refcounts/PySys_GetObject/incorrect/input.c:29:nn: note: borrowed reference returned by PySys_GetObject() allocated at:     return PySys_GetObject("foo");
tests/cpychecker/refcounts/PySys_GetObject/incorrect/input.c:29:nn: note: when PySys_GetObject() succeeds at:     return PySys_GetObject("foo");
tests/cpychecker/refcounts/PySys_GetObject/incorrect/input.c:29:nn: note: ob_refcnt is now refs: 0 + N where N >= 1
tests/cpychecker/refcounts/PySys_GetObject/incorrect/input.c:29:nn: note: returning at:     return PySys_GetObject("foo");
tests/cpychecker/refcounts/PySys_GetObject/incorrect/input.c:29:nn: warning: returning (PyObject*)NULL without setting an exception [enabled by default]
tests/cpychecker/refcounts/PySys_GetObject/incorrect/input.c:29:nn: note: PySys_GetObject does not find string at:     return PySys_GetObject("foo");
tests/cpychecker/refcounts/PySys_GetObject/incorrect/input.c:29:nn: note: returning at:     return PySys_GetObject("foo");
tests/cpychecker/refcounts/PySys_GetObject/incorrect/input.c:28:nn: note: graphical error report for function 'test' written out to 'tests/cpychecker/refcounts/PySys_GetObject/incorrect/input.c.test-refcount-errors.html'
