tests/cpychecker/refcounts/cplusplus/method/input.cc: In member function 'PyObject* Foo::test(int)':
tests/cpychecker/refcounts/cplusplus/method/input.cc:43:1: warning: ob_refcnt of return value is 1 too low [enabled by default]
tests/cpychecker/refcounts/cplusplus/method/input.cc:43:1: note: was expecting final ob_refcnt to be N + 1 (for some unknown N)
tests/cpychecker/refcounts/cplusplus/method/input.cc:43:1: note: due to object being referenced by: return value
tests/cpychecker/refcounts/cplusplus/method/input.cc:43:1: note: but final ob_refcnt is N + 0
tests/cpychecker/refcounts/cplusplus/method/input.cc:32:5: note: when considering value == (int)0 from tests/cpychecker/refcounts/cplusplus/method/input.cc:30 at:     if (i) {
tests/cpychecker/refcounts/cplusplus/method/input.cc:32:5: note: taking False path at:     if (i) {
tests/cpychecker/refcounts/cplusplus/method/input.cc:41:16: note: reaching:         return Py_None;
tests/cpychecker/refcounts/cplusplus/method/input.cc:32:5: note: ob_refcnt is now refs: 0 + N where N >= 1
tests/cpychecker/refcounts/cplusplus/method/input.cc:43:1: note: returning
tests/cpychecker/refcounts/cplusplus/method/input.cc:43:1: note: consider using "Py_RETURN_NONE;"
tests/cpychecker/refcounts/cplusplus/method/input.cc:31:1: note: graphical error report for function 'test' written out to 'tests/cpychecker/refcounts/cplusplus/method/input.cc.test-refcount-errors.html'
