tests/cpychecker/refcounts/PyArg_UnpackTuple/wrong-number-of-varargs/input.c: In function 'test':
tests/cpychecker/refcounts/PyArg_UnpackTuple/wrong-number-of-varargs/input.c:37:27: error: expected 3 vararg pointer(s); got 2
tests/cpychecker/refcounts/PyArg_UnpackTuple/wrong-number-of-varargs/input.c:29:1: note: graphical error report for function 'test' written out to 'tests/cpychecker/refcounts/PyArg_UnpackTuple/wrong-number-of-varargs/input.c.test-refcount-errors.html'
