tests/cpychecker/refcounts/PyObject_CallMethodObjArgs/incorrect/input.c: In function 'test':
tests/cpychecker/refcounts/PyObject_CallMethodObjArgs/incorrect/input.c:43:12: warning: argument 3 had type char[13] * but was expecting a PyObject* (or subclass) [enabled by default]
tests/cpychecker/refcounts/PyObject_CallMethodObjArgs/incorrect/input.c:43:12: warning: argument 4 had type char[4] * but was expecting a PyObject* (or subclass) [enabled by default]
tests/cpychecker/refcounts/PyObject_CallMethodObjArgs/incorrect/input.c:43:12: warning: argument 5 had type char[3] * but was expecting a PyObject* (or subclass) [enabled by default]
tests/cpychecker/refcounts/PyObject_CallMethodObjArgs/incorrect/input.c:43:12: warning: argument 6 had type char[3] * but was expecting a PyObject* (or subclass) [enabled by default]
tests/cpychecker/refcounts/PyObject_CallMethodObjArgs/incorrect/input.c:43:12: warning: argument 7 had type char[4] * but was expecting a PyObject* (or subclass) [enabled by default]
tests/cpychecker/refcounts/PyObject_CallMethodObjArgs/incorrect/input.c:43:12: warning: arguments to PyObject_CallMethodObjArgs were not NULL-terminated [enabled by default]
