Trace 0:
  Transitions:
  error: WrongArgCount()
  error: mismatching argument count in call to PyTuple_Pack
  Region("region-for-arg-gcc.ParmDecl('a')"):
    repr(): Region("region-for-arg-gcc.ParmDecl('a')")
    str(): Region("region-for-arg-gcc.ParmDecl('a')")
    r->ob_refcnt: refs: 0 + N where N >= 1
    r->ob_type: PointerToRegion(gcctype='struct PyTypeObject *', loc=gcc.Location(file='tests/cpychecker/refcounts/PyTuple_Pack/incorrect-arg-count/input.c', line=27), region=Region("region-for-type-of-arg-gcc.ParmDecl('a')"))
  Region("region-for-arg-gcc.ParmDecl('b')"):
    repr(): Region("region-for-arg-gcc.ParmDecl('b')")
    str(): Region("region-for-arg-gcc.ParmDecl('b')")
    r->ob_refcnt: refs: 0 + N where N >= 1
    r->ob_type: PointerToRegion(gcctype='struct PyTypeObject *', loc=gcc.Location(file='tests/cpychecker/refcounts/PyTuple_Pack/incorrect-arg-count/input.c', line=27), region=Region("region-for-type-of-arg-gcc.ParmDecl('b')"))
  Exception:
    (struct PyObject *)0 from tests/cpychecker/refcounts/PyTuple_Pack/incorrect-arg-count/input.c:28
