tests/cpychecker/refcounts/unrecognized_function3/input.c: In function 'call_to_unrecognized_function':
tests/cpychecker/refcounts/unrecognized_function3/input.c:33:1: warning: ob_refcnt of new ref from (unknown) foo is 1 too high [enabled by default]
tests/cpychecker/refcounts/unrecognized_function3/input.c:33:1: note: was expecting final ob_refcnt to be N + 0 (for some unknown N)
tests/cpychecker/refcounts/unrecognized_function3/input.c:33:1: note: but final ob_refcnt is N + 1
tests/cpychecker/refcounts/unrecognized_function3/input.c:32:8: note: new ref from (unknown) foo allocated at:     foo(42);
tests/cpychecker/refcounts/unrecognized_function3/input.c:32:8: note: when foo() succeeds at:     foo(42);
tests/cpychecker/refcounts/unrecognized_function3/input.c:32:8: note: ob_refcnt is now refs: 1 + N where N >= 0
tests/cpychecker/refcounts/unrecognized_function3/input.c:33:1: note: returning at: }
tests/cpychecker/refcounts/unrecognized_function3/input.c:30:1: note: graphical error report for function 'call_to_unrecognized_function' written out to 'tests/cpychecker/refcounts/unrecognized_function3/input.c.call_to_unrecognized_function-refcount-errors.html'
